### signup

POST http://localhost:8000/v1/api/shop/signup
Content-Type: application/json
x-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTMyOTVmOTVkZmFiN2VmZDg4NTZhN2IiLCJlbWFpbCI6InBoYW5xdWFuZ2R1b25nMjAwMkBnbWFpbC5jb20iLCJpYXQiOjE2OTc4MTQwMDksImV4cCI6MTY5Nzk4NjgwOX0.ZwZuDD-mQgnOUzkXKwsEMRAOtyCkc0E-y-Zk-NDBWEA

{
    "name": "phanquangduong",
    "email": "phanquangduong2002@gmail.com",
    "password": "12345"
}

